# Write it!

Typed/Debug:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '0.77'

Typed/Dig:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '0.79'

Typed/RedundantSafeNavigation:
  Description: 'TODO: Write a description of the cop.'
  Enabled: true
  VersionAdded: '0.77'
